### PR TITLE
x11: new configuration to follow i3 configuration changes.

### PR DESCRIPTION
**Pull request by PedroSFreitas**

### CODE REVIEW

**Review by bashM0nk3y — APPROVED** [review]
Most definitely an improvement..

**Review by bashM0nk3y — APPROVED** [review]
Thanks!

**Comment by ikstream** [comment]
Is there any problem on this pull request @PedroSFreitas

**Comment by PedroSFreitas** [comment]
@ikstream : accepting this PR will reflect in all other Window Manager (Openbox, Awesome, etc). It's not a problem itself, but we will definitely have to "fix" (improve the colors) in all those WMs to make sure they match with the colors on this PR.

**Comment by ikstream** [comment]
@PedroSFreitas I had a short look at it with the available options on the live ISO and it looks fine to me.
I am not sure if i covered everything important, and if my feeling for color matches that of the Rest :D

**Review by ikstream — APPROVED** [review]

**Comment by PedroSFreitas** [comment]
@ikstream, sounds good to me :).
Let's bring @noptrix for a final look and if everything is okay lest ship it! Agree?

**Comment by ikstream** [comment]
yup

**Comment by Luraktinus** [comment]
fixes the error bar, so far no issues

**Comment by ikstream** [comment]
@PedroSFreitas is this still needed, if yes we should fix the conflicts and merge it.

**Comment by PedroSFreitas** [comment]
> @PedroSFreitas is this still needed, if yes we should fix the conflicts and merge it.

Hi, @ikstream. No this PR is not needed anymore and can be fully closed.
However, just for the recorded, the fix introduced by https://github.com/BlackArch/blackarch-config-i3/pull/7 will not affected the colors terminal, the way this PR would do.

Cheers.

**Pull request closed without merging**
